#!/bin/bash


foreach BAS (outlet 12189500 12187500 12187000 12186500 ErmineGlacier 12186000 VistaGlacier DustyGlacier ChocolateGlacier CoolGlacier 12185000 SuiattleGlacier HoneycombGlacier )

set FULL_BAS_DIR = $1 # path for full basin output

	switch ($BAS)													# set column number for each basin in

		case 12189500								# Streamflow.Only file
			set COL_NUM = 3
			breaksw


		case 12186500				# Streamflow.Only file
			set COL_NUM = 6
			breaksw	
		
	endsw

### get flow values from full basin, otherwise some stream output locations will be outside mask

./dhsvm3hr.streamflow.only_2_dly.q.cms.scr $FULL_BAS_DIR/Streamflow.Only $FULL_BAS_DIR/$BAS.streamflow.daily.cms.txt $COL_NUM

./dhsvm.3hr.q.scr $FULL_BAS_DIR/Streamflow.Only $FULL_BAS_DIR/$BAS.streamflow.3hr.cms.txt $COL_NUM


end
